# Generated by Django 5.1.6 on 2025-07-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deskdrop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="spaces/"),
        ),
    ]
